---

  - name: Configure Docker TLS on AWS EC2
    block:
            - name: Configure Docker for TLS
              script: docker_tls.sh  `curl -s http://169.254.169.254/latest/meta-data/public-hostname`
              become: false
              
            - name: Copy Docker service file to hosts
              copy:
                src: docker.service
                dest: /usr/lib/systemd/system/docker.service
                owner: root
                group: root
                mode: '0644'

            - name: Store certs files locally 
              fetch:
                  src: .docker/{{ item }}
                  dest: "{{ docker_certs_folder }}/{{ inventory_hostname }}/{{ item }}"
                  flat: yes
              become: false
              with_items:
                - 'ca.pem'
                - 'cert.pem'
                - 'key.pem'
                   
            - name: Start Docker service
              service:
                name: docker
                state: started
                enabled: yes