---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: docker
   
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes